name: Build and Deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - main  # Or 'master' if that's your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3' # Or your Ruby version, check your Gemfile.lock
          bundler-cache: true

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --trace
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site